- stat: path=/var/www/web
  register: p

- debug: msg="Path exists and is a directory"
  when: p.stat.isdir is defined and p.stat.isdir

- name: install laravel
  shell: cd /var/www && composer create-project --prefer-dist laravel/laravel web
  when: not p.stat.isdir is defined

- file:
    path: /var/www/web/storage
    mode: 0777
    recurse: yes

- file:
    path: /var/www/web/bootstrap
    mode: 0777
    recurse: yes

- name: update config .env
  template: src=example.env dest=/var/www/web/.env
  notify:
    - artisan config:cache

- name: change web owner
  shell: cd /var/www && chown -R www-data:www-data web/
  when: p.stat.isdir is defined and p.stat.isdir
  notify:
      - Restart php-fpm (Debian)
      - Restart nginx


